apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

bases:
  - ../../../tenants/mlflow-demo/argocd/projects/overlays/default
  - ../../../tenants/mlflow-demo/argocd/apps/app-of-apps/overlays/default
  - ../../../tenants/mlflow-demo/argocd/applicationsets/overlays/default

patches:
  - path: patch-applicationset-repo-revision.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
  - path: patch-application-repo-revision.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
  # Uncomment patches to disable automatic sync
  # - path: patch-applicationset-manual-sync.yaml
  #   target:
  #     group: argoproj.io
  #     version: v1alpha1
  #     kind: ApplicationSet
  # - path: patch-application-manual-sync.yaml
  #   target:
  #     group: argoproj.io
  #     version: v1alpha1
  #     kind: Application
