apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-demo-app-of-aps
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: mlflow-demo-tenant
  source:
    path: clusters/mlflow-demo/argocd
    repoURL: https://github.com/strangiato/mlflow-demo-cluster-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
